// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc706.SussexCode.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc706.SussexCode.Robot;
import org.usfirst.frc706.SussexCode.RobotMap;

/**
 *
 */
public class AutonomousDrive extends Command {
	
	double driveSpeed;
	int driveDistance;
	private double encCurrentPos;
	private double encLastPos;
	private double trueCount = 0;
	boolean done = false;
	
    public AutonomousDrive(int distance, double speed) {
    	driveSpeed = speed;
    	driveDistance = distance;
     }

    protected void initialize() {
    }

    protected void execute() {
    	if(trueCount < driveDistance){
	    	Robot.chassis.move(driveSpeed, driveSpeed);
	    	detectDistanceTravelled();
    	}else{
    		Robot.chassis.move(0, 0);
    		done = true;
    	}
    	
    }

    protected boolean isFinished() {
        return done;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
    protected void detectDistanceTravelled() { //Calculates real distance from encoder values
    	encCurrentPos=RobotMap.rightDriveEnc.getValue();
    	if(encCurrentPos<encLastPos) {
    		trueCount+=(encLastPos-encCurrentPos);
    	}
    	if(encCurrentPos>encLastPos+3500) {
    		trueCount+=4096-encCurrentPos;
    	}
    	encLastPos=encCurrentPos;
    }
}
