// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc706.SussexCode.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc706.SussexCode.Constants;
import org.usfirst.frc706.SussexCode.Robot;

/**
 *
 */
public class Climb extends Command {
	
	private double driveSpeed = Constants.Speeds.WINCH_DRIVE_SPEED;

    public Climb() {
    	
    }

    protected void initialize() {
    	
    }

    protected void execute() {
    	
    	//put arm in place
    	Timer.delay(0.5);
    	new ExtendHook();
    	Timer.delay(0.5);
    	//lower arm
    	Timer.delay(0.5);
    	new EngageWinch();
    	Timer.delay(0.5);
    	Robot.chassis.move(driveSpeed, driveSpeed);
    }

    protected boolean isFinished() {
    	return true;
    }


    protected void end() {
    	Robot.chassis.move(0, 0);
    }

    protected void interrupted() {
    }
}
